### ISSUE TITLE
Question about the roadmap

### ISSUE THREAD

**Issue by croqaz** [atom/watcher#109]
Hi,

This is a question about this specific lib and has nothing to do with Atom.

I'm wondering what's the difference between this lib and https://github.com/atom/node-pathwatcher
I can see that this package has way more documentation than atom/node-pathwatcher and is still version 0.0.x , but seems to receive more love...

I'm looking for an alternative to chokidar, even if it's not that stable yet.

So my question is: what's the roadmap for this lib? Is it intended to be the default watcher for Atom?

Thank you

**Comment by smashwilson** [comment]
>  Is it intended to be the default watcher for Atom?

That is our intention :smile:

atom/atom#16124 is the pull request to add this library as a backing implementation for Atom's [PathWatcher API](https://atom.io/docs/api/v1.23.3/PathWatcher), and then I'd like to gradually replace node-pathwatcher uses with the watcher API throughout Atom core and the bundled packages. I'll likely bump this to 1.0.0 just before that's merged.

Watch for some activity on that front when I'm back from paternity leave, which will officially be about a week from now.

I will note that I likely won't be implementing additional features for a while after that happens - there's some other work I'd like to get back to on other parts of the system that are more urgent. I'd be happy to merge PRs from any other interested contributors in the meantime, though (hint, hint :wink:)

> I'm wondering what's the difference between this lib and https://github.com/atom/node-pathwatcher.

node-pathwatcher is the Atom team's previous iteration on this concept to support editor reloading, tree-view syncing, and so on. It's simpler, but more limited, than this one: watchers are non-recursive, fewer events are supported, and events are all delivered in-process, for example. This package is a replacement designed to make a clean break from the older API to address some of those limitations, specifically so that we could use it to back efforts like [the github package](http://blog.atom.io/2017/05/16/git-and-github-integration-comes-to-atom.html) and [language server integration](http://blog.atom.io/2017/09/12/announcing-atom-ide.html).

> I'm looking for an alternative to chokidar, even if it's not that stable yet.

Well awesome :sparkles: I'd love to hear how well it works for you! I think our biggest weakness right now is that this hasn't been run on that many different users' systems "in the wild" yet, to flush out all of the kinks and weird edge cases. Obviously we'll get that once we start shipping this on-by-default in Atom proper, but every bug we know about before then translates into a large set of users who won't get cross with us then.
